name: CI Tests on 03-api-solid

on:
  push:
    branches: ["03-api-solid"]
  pull_request:
    branches: ["03-api-solid"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test
